### ISSUE TITLE
MESA size

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#101]
The documentation contains different numbers describing the size of the MESA data set:

- https://sleepecg.readthedocs.io/en/latest/datasets.html says it contains 2056 annotated records.
- The table at the top of https://sleepecg.readthedocs.io/en/latest/classification.html says that 1970 MESA records were used to train the classifier.
- On the same page, the table in "Usage examples" says that 1971 records were used.

@hofaflo can you clarify how this fits together?

**Comment by hofaflo** [comment]
MESA contains 2056 records with sleep stage annotations, but heartbeat annotations are only available for 1971 of them. 1970 seems to be a typo.
