### ISSUE TITLE
Autosummary of public functions

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#103]
Currently, we list all functions and classes explicitly when generating our API docs, e.g.

```
.. autosummary::
   :toctree: generated
   :nosignatures:

   download_nsrr
   download_physionet
   export_ecg_record
   read_gudb
   read_ltdb
   read_mesa
   read_mitdb
   read_shhs
   read_slpdb
   set_nsrr_token
   ECGRecord
   SleepRecord
   SleepStage
```

However, these are our public objects (not starting with `_`), so is it not possible to tell the plugin to use all public functions so we don't have to list them explicitly?

**Comment by hofaflo** [comment]
It is possible - we actually did this initially, but switched to a manual approach in #55.

**Comment by cbrnr** [comment]
So what would change if we go back?

**Comment by hofaflo** [comment]
The names would be longer, e.g. `sleepecg.heartbeats.detect_heartbeats` instead of `sleepecg.detect_heartbeats` and we would lose the ability to structure the API overview page.

**Comment by cbrnr** [comment]
OK, then never mind. Maybe it's a good thing if we need to manually add a doc entry for any new public function.
