### ISSUE TITLE
Cannot reproduce benchmarks

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#109]
I noticed some changes in our benchmarks when I tried to reproduce it with the latest versions:

### Runtime
![runtime](https://user-images.githubusercontent.com/4377312/182553318-acbe5aed-6caa-4a13-8bdf-03ef9d94f205.png)

### Metrics
![metrics](https://user-images.githubusercontent.com/4377312/182553389-5003cd6a-c0ba-45f2-b176-723045fdaff8.png)

### Similarity
![similarity](https://user-images.githubusercontent.com/4377312/182553417-2249f469-57ef-49df-9cd5-dba33bd6375c.png)

@hofaflo any idea what is going on?

**Comment by berndporr** [comment]
How the Scot say here: "It wisnae me!"
There have been only minimal changes and the only substantial is actually a massive performance improvement for the WQRS detector which was written C style and now is using numpy slicing to the max. Been working on a new ECG detector benchmark called "JS" and noticed that WQRS always ran longest. Now similar to all the others.

**Comment by berndporr** [comment]
Actually just called "JA" but I think I should add the "!". ;) https://github.com/berndporr/JA-ECG-Benchmark

**Comment by cbrnr** [comment]
I will try if I can get the old results with the older version. If so, then pretty surely there must have been more substantial changes that led to a massive performance degradation. Not sure if we are talking about the same detector, I am only referring to `ecgdetectors.Detectors(fs).pan_tompkins_detector(ecg)`.

**Comment by berndporr** [comment]
It's git isn't it? If you suspect pan tompkins has been messed up then just look at the commit history and tell me where it is and not some vague "there must have been substantial changes". As I said I had a look at the commit history and I cannot see any changes. Feel free to get back to me with something specific.

**Comment by cbrnr** [comment]
No, I don't care. I thought you might want to know. That's all.

**Comment by berndporr** [comment]
ok

**Comment by cbrnr** [comment]
It seems like more (all?) detectors are different from our original benchmark, so it's likely something that's changed on our side or in our dependencies.

**Comment by cbrnr** [comment]
I tried Python 3.8 and older versions of our dependencies (as specified in `requirements-benchmark.txt`) as well as previous versions of SleepECG (up to v0.3.0) – I cannot reproduce the benchmarks results in our docs.

**Comment by hofaflo** [comment]
When working on the benchmarks in #22, I limited the number of records to 25 to reduce runtime while debugging. As pointed out in [this comment](https://github.com/cbrnr/sleepecg/pull/22#issuecomment-902533198), the slicing operation stayed in for too long (removed in 30ed383), and apparently I missed to recreate the plots.

**Comment by cbrnr** [comment]
Thanks, I will create new figures with all records.
