### ISSUE TITLE
Reading MESA edf file

### ISSUE THREAD

**Issue by dimzog** [cbrnr/sleepecg#122]
There seems to be an issue with

https://github.com/cbrnr/sleepecg/blob/61b15a8d03089db8afddcad341c8857a6f630756/sleepecg/io/sleep_readers.py#L653

There is no channel name 'ECG' in latest MESA release, do not know if there was before or when it was changed.

a list of current channel names is as follows
`['EKG',
 'EOG-L',
 'EOG-R',
 'EMG',
 'EEG1',
 'EEG2',
 'EEG3',
 'Pres',
 'Flow',
 'Snore',
 'Thor',
 'Abdo',
 'Leg',
 'Therm',
 'Pos',
 'EKG_Off',
 'EOG-L_Off',
 'EOG-R_Off',
 'EMG_Off',
 'EEG1_Off',
 'EEG2_Off',
 'EEG3_Off',
 'Pleth',
 'OxStatus',
 'SpO2',
 'HR',
 'DHR']`

**Comment by cbrnr** [comment]
Could you provide a minimal reproducible example please? I tried the following snippet, which worked without errors:

```python
from sleepecg import read_mesa, set_nsrr_token

set_nsrr_token("<INSERT_NSRR_TOKEN>")
mesa = read_mesa(records_pattern="0001*")
next(mesa)
```

**Comment by dimzog** [comment]
`
from mne.io import read_raw_edf

rec = read_raw_edf("PATH/TO/file.edf", verbose=False)
ecg = rec.get_data("ECG").ravel()
`

ValueError: picks ('ECG') could not be interpreted as channel names (no channel "['ECG']"), channel types (no type "ECG"), or a generic type (just "all" or "data")

**Comment by dimzog** [comment]
I do not use sleepecg's readers, the issue is located in an inner function that reads HR data from the edf files. 

https://github.com/cbrnr/sleepecg/blob/61b15a8d03089db8afddcad341c8857a6f630756/sleepecg/io/sleep_readers.py#L480-L682

This might worked for previous versions of MESA, but it does not now.
The aim of this issue was to bring this misbehavior to your notice.
