### ISSUE TITLE
Some inconsistencies

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#127]
I was wondering why the following classes are not exported (i.e. part of `sleepecg/io/__init__.py` and therefore also in the API docs):

- `sleepecg.io.sleep_readers.Gender`
- `sleepecg.io.sleep_readers.SubjectData`

These are "public" classes, and should therefore be exported (or made "private" by appending an underscore).

Similarly, `sleepecg.io.gudb.GUDB_MD5` is "public" (but not exported), I think here it would be consistent to rename to `_GUDB_MD5`.

@hofaflo WDYT?

**Comment by hofaflo** [comment]
I agree on all points!
