### ISSUE TITLE
How to deal with Numba?

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#132]
I am a bit unhappy that Numba is blocking our support for Python 3.11 (see #124). Since Numba is not a required dependency for us, would it be possible to still add Python 3.11 support but without Numba? What would we need to do to implement this (I'm sure we need to at least adapt our tests). Any suggestions @hofaflo?

**Comment by hofaflo** [comment]
I found a relatively elegant way to do this, I can push it to the python-311 branch in #124 if you like?

**Comment by cbrnr** [comment]
Yes, please go ahead!
