### ISSUE TITLE
Tests should not use `_heartbeat_detection`

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#14]
The tests still import the C implementation directly. We should use the public function instead and perform the tests with all three backends.

This raises the additional question: how do I build the C extension locally?

**Comment by hofaflo** [comment]
I'm with you on performing tests on all backends. I'd keep the tests for type- and valuechecks of the C extension though, to make sure possible future updates don't mess something up there. We could [mark them](https://docs.pytest.org/en/6.2.x/example/markers.html#marking-test-functions-and-selecting-them-for-a-run), disable them by default and only run them if required?

For building the C extension locally I usually use `pip install -e .[full]` (`[full]` makes sure `wfdb` and `numba` are installed, as those are required for testing).  `python setup.py build bdist_wheel` followed by `pip install <path-to-wheel>` should work as well.

**Comment by cbrnr** [comment]
> I'm with you on performing tests on all backends. I'd keep the tests for type- and valuechecks of the C extension though, to make sure possible future updates don't mess something up there. We could mark them, disable them by default and only run them if required?

Of course, I didn't mean to imply that we should drop the C extension tests. However, we could use the public function with `backend='c'` to perform these tests (and then add tests for the other backends if necessary).

> For building the C extension locally I usually use `pip install -e .[full]` (`[full]` makes sure `wfdb` and `numba` are installed, as those are required for testing). `python setup.py build bdist_wheel` followed by `pip install <path-to-wheel>` should work as well.

Thanks, I'll go with `pip install -e .[full]` then.

**Comment by hofaflo** [comment]
#18 marks the module containing the C extension tests, so they can be excluded by calling `pytest -m "not c_extension"`.
