### ISSUE TITLE
[JOSS Review] Information about "Movement Data"

### ISSUE THREAD

**Issue by richrobe** [cbrnr/sleepecg#155]
(as part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/5411))

In the README, you wrote: "Based only on ECG (and to a lesser extent also movement data), `SleepECG` provides functions for [...]". I'm wondering where the movement data comes from since you didn't mention it elsewhere and also have no functions for importing, processing, and extracting features from acceleration or actigraphy data.

**Comment by cbrnr** [comment]
You're right, actigraphy data has been on our todo list ever since, but so far there is nothing in the package. I'll remove the part about movement data (we can add it again once we actually support it).

**Comment by richrobe** [comment]
Alright! Let me know when you're interested in including actigraphy data as we're also working on sleep staging using wearable sensors (actigraphy, ECG, respiration, ...) and have some code lying around for feature extraction and classification from actigraphy data that you might be interested in using 🙂

**Comment by cbrnr** [comment]
This sounds great! We could discuss this anytime, it's just that I don't have a lot of time currently to actually implement anything as substantial as that.
