### ISSUE TITLE
[JOSS Review] Paper Remarks

### ISSUE THREAD

**Issue by richrobe** [cbrnr/sleepecg#156]
(as part of the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/5411))

The paper is easy written, easy to follow, and nicely outlines the need of the `SleepECG` package. It provides a good motivation, especially regarding the reproducibility of the existing approaches. Just some minor comments:
- To better understand the scope of the package at first sight, an overview image showing the typical workflow for ECG-based sleep staging (data download, data cleaning, pre-processing, feature extraction, training, ...), and where `SleepECG` could help in this process (namely everywhere) would be beneficial.
- Could you add some more information on the pre-trained classifiers you used in your paper in terms of network architecture, training & evaluation process, etc.? Is there already a publication on it (if yes, could you link it?)

**Comment by cbrnr** [comment]
Thanks, adding an overview figure is a great idea!

Regarding our pre-trained classifiers, we don't have a publication on that yet, so this will explained in all the details there. How much information do you think makes sense here? The scripts that we used to train are available inside [`examples/classifiers/`](https://github.com/cbrnr/sleepecg/tree/main/examples/classifiers), but I feel like this is way too much detail for this paper. What about including what features we used (all time-based and frequency-based HRV features, the recording starting time, age, and gender) as well as mention that we used a neural network with gated recurrent units (GRUs)? Would that be sufficient?

**Comment by richrobe** [comment]
Yes, that sounds good! 🙂

**Comment by cbrnr** [comment]
I've updated the paper, please [take a look](https://github.com/cbrnr/sleepecg/suites/12925945492/artifacts/698256375) and let me know if you would like me to change anything. If you're happy with the changes, feel free to close this issue.

**Comment by cbrnr** [comment]
@richrobe is the overview figure I've added OK? I didn't really know what to include, so please feel free to comment if you have more ideas on how to improve that figure.

https://raw.githubusercontent.com/openjournals/joss-papers/joss.05411/joss.05411/10.21105.joss.05411.pdf

**Comment by richrobe** [comment]
Sorry - no, the figure gives a nice overview. Maybe play around with the layout and colors a little bit to make it a little more "appealing"... 🙂

**Comment by cbrnr** [comment]
OK, I tried by adding a little color (from the colorbrewer palette), so hopefully it's a bit nicer now.
