### ISSUE TITLE
add requirements.txt to allow quick installation of dependencies?

### ISSUE THREAD

**Issue by tompollard** [cbrnr/sleepecg#163]
This is a quick issue relating to the JOSS review comments at: https://github.com/openjournals/joss-reviews/issues/5411#issuecomment-1548163405

For development I'd usually expect to see a file containing the dependencies somewhere (e.g. requirements.txt or environment.yml). Does this exist? I see that the dependencies are listed in README.md, but it would be nice to have a file that can be used by package managers (e.g. pip, conda).

**Comment by cbrnr** [comment]
All (required and optional) dependencies are listed in `pyproject.toml`, and `pip` uses this file for installation. For example, if you want to set up your dev environment, you can do so with `pip install -e ".[dev]"` from the root folder of your clone, which will install all dependencies necessary for development.

I would like to avoid duplicating (and keeping in sync) requirements in a separate `requirements.txt`, unless there is a specific use case that is not covered by `pyproject.toml` – maybe you have something in mind that I'm missing?

**Comment by tompollard** [comment]
@cbrnr you make a good point, there's no particularly strong reason to have a requirement.txt file here (I think it's just become habit to see one!).
