### ISSUE TITLE
Add figures to paper (heartbeat detection metrics; sleep staging)?

### ISSUE THREAD

**Issue by tompollard** [cbrnr/sleepecg#168]
This is a quick issue relating to the JOSS review comments at: https://github.com/openjournals/joss-reviews/issues/5411#issuecomment-1548163405

There is a metrics figure at https://sleepecg.readthedocs.io/en/stable/heartbeat_detection/#usage that I think would be a nice addition to the paper.

Given the focus of the package is sleep staging, it would also be nice to add a figure demonstrating the sleep staging functionality. A (ideally non-cheat!) version of the hypnogram at https://sleepecg.readthedocs.io/en/stable/plot/ might be a good one to include?

Neither of these are necessary, so please feel free to close this issue if you disagree or don't think it is worth the trouble!

**Comment by cbrnr** [comment]
I think this is a great suggestion! I assume that by "non-cheat" version you are referring to the fact that our figure shows sleep stages based on the labels in the data, and you would prefer labels predicted by a classifier? What about including the hypnogram from [`examples/try_ws_gru_mesa.py`](https://github.com/cbrnr/sleepecg/blob/main/examples/try_ws_gru_mesa.py)? It has only two stages, so if you prefer a plot with three stages I'd have to adapt the example (shouldn't be too much effort).

![Figure_1](https://github.com/cbrnr/sleepecg/assets/4377312/716a7a64-4b12-42fd-b8ff-ea3d62672226)

**Comment by cbrnr** [comment]
Regarding the metrics figure, I think that it definitely adds value, but I'm not sure how many figures we can and should include in the paper. As part of the review process, I've already added an overview figure, so we currently have two figure (the overview and R peak detector runtimes). I would like to add a hypnogram (to support highlighting the focus of SleepECG) and maybe skip the detector metrics. Let me know what you think (and if you would like a two stage or three stage hypnogram)!

**Comment by tompollard** [comment]
> I would like to add a hypnogram (to support highlighting the focus of SleepECG) and maybe skip the detector metrics. Let me know what you think (and if you would like a two stage or three stage hypnogram)!

Skipping the metrics makes sense for the reasons you say. I like the idea of a hypnogram. The one you've shown above would be fine I think, perhaps with a note to say that multistage classification is also supported?

**Comment by cbrnr** [comment]
I've added the hypnogram to the paper.
