### ISSUE TITLE
Cite relevant codebases in JOSS paper

### ISSUE THREAD

**Issue by tompollard** [cbrnr/sleepecg#169]
This is a quick issue relating to the JOSS review comments at: https://github.com/openjournals/joss-reviews/issues/5411#issuecomment-1548163405

I am not familiar with the literature on sleep-staging with ECG, but I do see there are one or two open source codebases that claim to enable ecg-based sleep staging. I wonder whether these should be briefly mentioned?

e.g. should comparisons be made to https://github.com/bdsp-core/ecg_respiration_sleep_staging? The repo doesn't look completely baked (e.g. "[training_code_still_messy](https://github.com/bdsp-core/ecg_respiration_sleep_staging/tree/master/training_code_still_messy))", so perhaps it reinforces your point that "either the processing pipeline or the dataset used to generate the published results are not publicly available."

**Comment by cbrnr** [comment]
I agree with both points that we should probably mention related packages and that these are not as readily usable and as open as SleepECG. I don't want to start a discussion on the pros and cons of each package, so maybe briefly mention that there are other packages out there should be sufficient.

Do you have any additional packages that you found other than the one you mentioned?

**Comment by tompollard** [comment]
> I don't want to start a discussion on the pros and cons of each package, so maybe briefly mention that there are other packages out there should be sufficient.

I agree, just some quick pointers to existing repos would be enough.

> Do you have any additional packages that you found other than the one you mentioned?

Like you say, there doesn't seem to be much around. The repos that I came across during a quick search included:

- https://github.com/Acrophase/Sleep_Staging_KD
- https://github.com/pickus91/ECG-Sleep-Stage-Classification
- https://github.com/ojwalch/sleep_classifiers
- https://github.com/bzhai/multimodal_sleep_stage_benchmark

I'll leave you to decide which of these are worth mentioning, if any!

**Comment by cbrnr** [comment]
I've mentioned all but the second one (which does not really contain anything substantial).
