### ISSUE TITLE
Question regarding classifiers

### ISSUE THREAD

**Issue by lili084** [cbrnr/sleepecg#198]
I want to use this program to recognize my own ECG data. Is this possible? Or to put it another way, are the parameters of the classifiers already trained? Thank you very much for your reply

**Comment by cbrnr** [comment]
Yes, we ship three pre-trained classifiers that you can use to classify your own ECG time series. Examples are not yet available on our stable docs, but you can check them out here: https://sleepecg.readthedocs.io/en/latest/examples/ (in particular, see the section "Sleep staging custom data").

**Comment by lili084** [comment]
Thank you very much for your reply. The function has been implemented, and I sincerely wish sleepecg better and better.
