### ISSUE TITLE
Add our detector to neurokit

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#25]
I know the package is still new, but I just did a Google search for "python ecg peak detection", and SleepECG doesn't show up in the first eight pages (we all know that no one ever goes to page 2). Any ideas on how we could increase our visibility? I think people should really be able to find SleepECG's Pan-Tompkins peak detector, because it is the best:tm: implementation available.

**Comment by hofaflo** [comment]
It's on the top of [PyPI search results](https://pypi.org/search/?q=ecg+peak+detection&o=) though :D

Unrelated to heartbeat detection, but we could add `nsrr` to the tags (and maybe mention it in the readme), since we provide the only Python interface for sleepdata.org?

**Comment by cbrnr** [comment]
> It's on the top of PyPI search results though :D

🤯 - how come?

> Unrelated to heartbeat detection, but we could add nsrr to the tags (and maybe mention it in the readme), since we provide the only Python interface for sleepdata.org?

Yes, a section on which databases we can read from would be useful anyway. I'm not sure about that tag, I don't think that it is that common, and if we have it in our `README.md` I think this will be sufficient.

**Comment by cbrnr** [comment]
A little post on my blog might also help – planned for September.

**Comment by DominiqueMakowski** [comment]
Just chiming in here after @cbrnr mentioned it to me on another issue. Great package and very promising performance indeed (and awesome benchmark stats :)

Another way to increase visibility and download of sleepecg's detector could be to enable its usage from other packages, such as [neurokit's](https://github.com/neuropsychology/NeuroKit). We could do that by adding a function [here](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_findpeaks.py), and if you prefer not to duplicate the code, we could directly add `sleepecg` as an optional dependency and call it. Let me know what you think :)

**Comment by cbrnr** [comment]
Thanks @DominiqueMakowski! I think adding `sleepecg` as a soft dependency and adding a new option `method="sleepecg"` would be great! I can submit a PR if you want.

**Comment by LegrandNico** [comment]
Just jumping into this discussion a bit late, but it turns out that if SleepECG is "the best™️ implementation available" that would also be a nice update to [Systole](https://github.com/embodied-computation-group/systole) for the next release :pray:, I can add the dependencies and a new option as mentioned.
Great work on improving this algorithm!

**Comment by cbrnr** [comment]
Sure, this would be great! It's the fastest implementation of a Pan-Tompkins detector available for Python to my knowledge - I wouldn't call it the best!

**Comment by cbrnr** [comment]
I'll close this here and let the package maintainers decide if they want to integrate our detector. We can then discuss in corresponding PRs in their repos.
