### ISSUE TITLE
Remove warning suppression in `_dummy_mesa_edf` 

### ISSUE THREAD

**Issue by hofaflo** [cbrnr/sleepecg#40]
[This](https://github.com/cbrnr/sleepecg/blob/main/sleepecg/test/test_sleep_readers.py#L26-L28) should be unnecesary once the issue is fixed upstream by holgern/pyedflib#151.

**Comment by cbrnr** [comment]
Fixed. I guess you would want to wait for their next release?

**Comment by hofaflo** [comment]
Yep!

**Comment by cbrnr** [comment]
OK! Maybe they even add Python 3.10 wheels.
