### ISSUE TITLE
Add Python 3.10

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#44]
As discussed in #41, we need to wait for the following packages to provide binary wheels for Python 3.10:

- Numba (numba/numba#7562)
- PyEDFlib

**Comment by hofaflo** [comment]
Required changes:

- [ ] Add Python 3.10 classifier in `setup.cfg`
- [ ] Stop skipping `cp310-*` in `pyproject.toml`:`tool.cibuildwheel`

**Comment by hofaflo** [comment]
Numba v0.55.0 is [released](https://github.com/numba/numba/releases/tag/0.55.0), so we'll just need to wait for pyEDFlib now.

**Comment by cbrnr** [comment]
Nice! Yes, I am waiting really hard for that one...

**Comment by hofaflo** [comment]
closed by #75
