### ISSUE TITLE
Build wheels for ARM64 Mac

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#5]
Given that Apple has started switching all of their products to ARM64, I think it would be useful if we also provided corresponding wheels. According to [cibuildwheel's docs](https://github.com/pypa/cibuildwheel#cibuildwheel), this should work for Python 3.8+.

**Comment by hoechenberger** [comment]
You may want to ask @dengemann for help, he's got one of those machines :)
I will have access to one by the end of August, too, and could help you build / test.

**Comment by cbrnr** [comment]
Thanks @hoechenberger, this is very much appreciated because I will probably not be able to test this myself. FWIW, if by "have access" you mean "get a MacBook M1", you might want to hold off until the fall where Apple is rumoured to release M1X/M2-based MacBook Pros (14" and 16")...

**Comment by hoechenberger** [comment]
> if by "have access" you mean "get a MacBook M1", you might want to hold off until the fall where Apple is rumoured to release M1X/M2-based MacBook Pros (14" and 16")...

Yep, I know, but @agramfort promised I'll get an M1 that's currently in use by an intern who won't need it anymore in a few weeks :) So – we already have this computer, it's not a new purchase. Thanks for the head-up anyway!

**Comment by agramfort** [comment]
@cbrnr did you consider using numba instead of a c extension?

**Comment by cbrnr** [comment]
@agramfort we tried Cython, which did not really speed things up a lot and in the end looked pretty much as C-like as the C source we now have. We didn't try Numba though AFAIK. We are planning to ship a pure Python implementation as a fallback (or manual) option, which we can try to speed up with Numba.

I guess you are asking because C extensions are generally a PITA? I agree, but at least the build process is nicely integrated into standard Python packaging machinery (`setup.py`), so no custom `Makefiles` or the like are required (`pip install .` in the root does everything). We also build wheels for all platforms and Python versions in CI.

**Comment by agramfort** [comment]
>
> I guess you are asking because C extensions are generally a PITA? I agree,
> but at least the build process is nicely integrated into standard Python
> packaging machinery (setup.py), so no custom Makefiles or the like are
> required (pip install . in the root does everything). We also build
> wheels for all platforms and Python versions in CI.
>
I am asking as shipping binaries for all platforms is a pain. If you only
put sources on pypi then you require windows users to have a compiler.

**Comment by cbrnr** [comment]
> I am asking as shipping binaries for all platforms is a pain. If you only
put sources on pypi then you require windows users to have a compiler.

Yes, but the idea here is that we provide binary wheels for all platforms.

**Comment by hoechenberger** [comment]
it will be extremely simple via conda-forge though :) and for Linux, there's manylinux if that matters, no?
I would just build and deploy for all platforms on the CI system -- that's how I do it with my MNE installers.

**Comment by agramfort** [comment]
@hoechenberger not everybody uses conda and ask the sklearn maintainers what it takes to maintain binaries. Maybe a good watch with some advice on that matter https://www.youtube.com/watch?v=6a9D9WL6ZjQ

**Comment by cbrnr** [comment]
@hoechenberger @agramfort that's exactly how we're already doing it for PyPI.
