### ISSUE TITLE
Google search result for website points to a 404

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#59]
Google shows this URL when searching for "sleepecg": https://sleepecg.readthedocs.io/en/latest/generated/sleepecg.html

This page doesn't exist anymore. Any idea if this is a problem we can solve? The correct URL is https://sleepecg.readthedocs.io/en/stable/ BTW.

**Comment by hofaflo** [comment]
Read the Docs allows to create [redirects](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#page-redirects), so I set one up from `generated/sleepecg.html` to `index.html`. This took a few minutes to be applied, but seems to work now :)

Further optimization of the google results might be possible using the [Google Search Console](https://search.google.com/search-console). Verification works with a html meta tag on the doc index page, like on [this test branch](https://search.google.com/search-console). There's also an [SEO guide](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html) from RTD we could follow.

**Comment by cbrnr** [comment]
Thanks @hofaflo! Do you know why Google had that URL? Did we use that before and then change it? If so, what change triggered the different URL?

**Comment by hofaflo** [comment]
Since #55, the main readme doesn't link to the main page of the API reference (which was generated by autosummary) anymore, but to the doc overview page.
