### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by hoechenberger** [cbrnr/sleepecg#6]
Hello @cbrnr, congrats to the public release!

Are you planning to have a package on `conda-forge` too? I can help you create it (or create it for you ;)). Just let me know!

**Comment by cbrnr** [comment]
Thanks @hoechenberger, if you have time to do it please go ahead! We can include the conda install command in our README once it's available.

**Comment by hoechenberger** [comment]
WIP:
https://github.com/conda-forge/staged-recipes/pull/15932

**Comment by hoechenberger** [comment]
Just FYI, the recipe has been merged, but there's currently a CI problem that prevents the packages from being built & deployed. Hopefully this will be resolved soon.

**Comment by cbrnr** [comment]
Thanks @hoechenberger! Let us know when it is available and we can include a link in our `README.md`. Also, we will release 0.3 soon so you don't have to vendor `LICENSE` anymore (I guess this will require an update to the formula?).

**Comment by hoechenberger** [comment]
> Also, we will release 0.3 soon so you don't have to vendor `LICENSE` anymore (I guess this will require an update to the formula?).

That will be just a really tiny change, I'll take care of this once 0.3 has been released :)

**Comment by hoechenberger** [comment]
The package is now available from conda-forge:

https://anaconda.org/conda-forge/sleepecg

Before doing an official announcement, we should probably ensure it actually works as intended 😅 I haven't tested the various "backends"; my understanding is that there's Python, numba, and C, right? They all SHOULD work but would be good to check

**Comment by cbrnr** [comment]
Nice! You can test them with our tests. Do you have `numba` as a dependency or is it just optional? In any case, we fall back to pure Python if neither C nor Numba are available (so the order of preference is C -> Numba -> Python).

**Comment by hoechenberger** [comment]
I included all optimal dependencies 😅 and linked the C module against NumPy
Are the tests included in the sdist?

I'm out for coffee, will have a look at this later today 💪

**Comment by hofaflo** [comment]
Just ran the tests, seems to work, thanks @hoechenberger! :)

**Comment by cbrnr** [comment]
Tests are not included in the sdist. It seems like we should just create a `MANIFEST.in` containing `*`.

**Comment by hoechenberger** [comment]
@cbrnr sounds fair!

@hofaflo awesome, thanks! I think it's safe to announce the conda-forge package then!

**Comment by cbrnr** [comment]
Thanks @hoechenberger! If you have any idea how we can increase visibility, let us know at #25!
