### ISSUE TITLE
Website links broken

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#60]
Links on the [documentation website](https://sleepecg.readthedocs.io/en/stable/) are currently broken (at least the way they are rendered):

<img width="776" alt="Screen Shot 2022-01-08 at 12 04 01" src="https://user-images.githubusercontent.com/4377312/148641772-03dab7ac-bdff-4fbe-866c-56638d50de2e.png">

**Comment by hofaflo** [comment]
This is fixed by switching to MyST in #36, will be applied to `stable` with the next release.

**Comment by cbrnr** [comment]
Then let's try to release early next week!

**Comment by cbrnr** [comment]
@hofaflo do you want to include anything else in the release?

**Comment by hofaflo** [comment]
no, that should be it :)

**Comment by cbrnr** [comment]
Great! Feel free to cut the release then!

**Comment by hofaflo** [comment]
done 🎉
