### ISSUE TITLE
Formatting of readers in docs

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#73]
Should the readers in the first column on https://sleepecg.readthedocs.io/en/stable/datasets.html get formatted as code (i.e. enclosed in backticks)?

**Comment by hofaflo** [comment]
Good question, the monospaced font would be nice but I'm not so sure about the color 😅 

![image](https://user-images.githubusercontent.com/22592497/150417555-349aaed5-1aae-4e55-8b9f-18050970ee2e.png)

Now that I think about it, we could select a less striking color for inline code to avoid things like this:

![image](https://user-images.githubusercontent.com/22592497/150417947-14529aeb-b2ad-45c4-a5a4-d89af843c216.png)

**Comment by cbrnr** [comment]
Yes, that docstring looks messy. Maybe a grayish color?

**Comment by hofaflo** [comment]
Like this?
![image](https://user-images.githubusercontent.com/22592497/150519818-160dbfaa-0182-444c-bcc5-4d2c6fa9f4a1.png)

**Comment by cbrnr** [comment]
Bit hard to read, what about black? Also, why is the "optional" not pink anymore?

I also wonder if the theme we're using supports a dark mode, do you know?

**Comment by cbrnr** [comment]
Regarding the colors, maybe function/class names should stay pink and monospaced text should be black? But this is probably not possible I assume.

**Comment by hofaflo** [comment]
Black is better readable, yes!
![image](https://user-images.githubusercontent.com/22592497/150589453-b618a4c6-1894-4644-af2c-74c6d87b614e.png)

Dark mode looks like a [no(t yet)](https://github.com/pydata/pydata-sphinx-theme/issues/458)

The 'optional' changed together with the inline code, I couldn't find an option to prevent this in the default [theme.css](https://github.com/pydata/pydata-sphinx-theme/blob/master/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/static/styles/theme.css) :/

We could switch to [furo](https://github.com/pradyunsg/furo), which has a dark mode and displays inline code similar to GitHub. It doesn't have a menu bar at the top though:
![image](https://user-images.githubusercontent.com/22592497/150590312-5ecc5909-b213-44d2-8bdf-90cfbe5644d0.png)
![image](https://user-images.githubusercontent.com/22592497/150590365-307a82f5-da79-409e-9b48-ff18176a6326.png)

**Comment by cbrnr** [comment]
> We could switch to furo

No objection, if you don't mind the missing top navbar I'd say let's do it! I assume the GitHub icon and the RTD version switcher still works?

**Comment by hofaflo** [comment]
ad navbar: I think it's fine, I'd just put 'API' last as its the only element with a dropdown

ad GitHub: no, but the link could be in the left navigation bar ([example](https://pradyunsg.me/furo/))

ad version switcher: that should be part of RTD, so nothing to worry here

**Comment by cbrnr** [comment]
Fixed in #74.
