### ISSUE TITLE
Quick release 0.4.2?

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#79]
@hofaflo should we make a quick v0.4.2 release so that we get Python 3.10 support and the new website design out there? The classification stuff will go into v0.5.0 then.

**Comment by cbrnr** [comment]
Also, what is up with the conda package? It seems to be stuck at 0.4.0. Personally, I'd not mention any conda-related things here, because PyPI is the official method and everything works.

**Comment by hofaflo** [comment]
ad release: I'd put everything into v0.5.0, but if you prefer we can make a v0.4.2

ad conda: looks like @hoechenberger fixed that (conda-forge/sleepecg-feedstock#4), thanks :)

**Comment by cbrnr** [comment]
OK, let's do v0.5.0 then, shouldn't be too long.
