### ISSUE TITLE
Publication on prediction performance

### ISSUE THREAD

**Issue by chenxuesongTHU** [cbrnr/sleepecg#80]
Hi, 
    I am so excited to see your wonderful work! Is there any release about the prediction performance of the ECG signals only or comparison with EEG signals? 

Thanks a lot~

**Comment by cbrnr** [comment]
Hi @chenxuesongTHU! Thank you for your interest in our work. We are currently still working on this evaluation. My plan is to also submit to a peer-reviewed journal eventually, but unfortunately I cannot tell you a timeframe right now.

**Comment by cbrnr** [comment]
Closing because the question is answered. I'm preparing a publication about the package, and another one about sleep staging performance. If they are accepted I'll add them to the README.md.
